export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
export const IS_ADMIN = 'IS_ADMIN'
export const IS_USER = 'IS_USER'
export const TOKEN_DEVICE = 'TOKEN_DEVICE'